version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@14.1.0
  coveralls: coveralls/coveralls@2.2.5

executors:
  gradle:
    docker:
      - image: cimg/android:2026.02-browsers
    resource_class: medium
  macos:
    macos:
      xcode: 26.3.0
    resource_class: m4pro.medium
  windows:
    machine:
      image: windows-server-2022-gui:current
    resource_class: windows.medium

commands:
  extract_m2_version:
    steps:
      - run:
          name: Extract LocalRepo name
          command: |
            echo "m2-v1" > .circleci-m2-cache-key.txt
  extract_gradle_version:
    steps:
      - run:
          name: Extract Gradle version
          command: |
            GRADLE_VERSION=$(grep -o 'gradle-[0-9.]*' gradle/wrapper/gradle-wrapper.properties | cut -d- -f2)
            echo "$GRADLE_VERSION" > .circleci-gradle-cache-key.txt
  extract_kotlin_version:
    steps:
      - run:
          name: Extract Kotlin version
          command: |
            KOTLIN_VERSION=$(grep 'kotlin =' gradle/libs.versions.toml | cut -d'"' -f2)
            echo "$KOTLIN_VERSION" > .circleci-kotlin-cache-key.txt
  restore_gradle_cache:
    steps:
      - restore_cache:
          keys:
            - gradle-v1-{{ checksum ".circleci-gradle-cache-key.txt" }}
            - gradle-v1-
  restore_konan_cache:
    steps:
      - restore_cache:
          keys:
            - konan-v1-{{ checksum ".circleci-kotlin-cache-key.txt" }}
            - konan-v1-
  restore_m2_cache:
    steps:
      - restore_cache:
          keys:
            - m2-v1-{{ checksum ".circleci-m2-cache-key.txt" }}
            - m2-v1-
  ensure_gradle_wrapper:
    steps:
      - run:
          name: Ensure Gradle Wrapper JAR
          command: |
            mkdir -p gradle/wrapper
            if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
              GRADLE_VERSION=$(sed -n 's/.*gradle-\(.*\)-bin\.zip.*/\1/p' gradle/wrapper/gradle-wrapper.properties)
              curl -L --fail --silent -o gradle/wrapper/gradle-wrapper.jar \
                "https://raw.githubusercontent.com/gradle/gradle/v${GRADLE_VERSION}/gradle/wrapper/gradle-wrapper.jar"
            fi
  accept_android_licenses:
    steps:
      - run:
          name: Accept Android licenses
          command: yes | sdkmanager --licenses || true
  configure_kotlin_native:
    steps:
      - run:
          name: Configure Kotlin Native
          command: echo "kotlin.native.ignoreDisabledTargets=true" >> gradle.properties
  run_build:
    steps:
      - run:
          name: Run build
          command: ./gradlew build --no-daemon --stacktrace -x test
  run_tests:
    steps:
      # - run:
      #     name: Debug test paths
      #     command: |
      #       pwd
      #       ls
      #       ls library || true
      #       find . -type f | grep 'Test\.kt$' || true
      #       circleci tests glob "library/src/commonTest/kotlin/**/*Test.kt" "library/src/jvmTest/kotlin/**/*Test.kt" | tee /tmp/test-files.txt
      #       echo "Matched files:"
      #       cat /tmp/test-files.txt || true
      # - run:
      #     name: Debug CircleCI test glob on Windows
      #     shell: bash.exe
      #     command: |
      #       echo "PWD:"
      #       pwd

      #       echo "Backslash glob:"
      #       circleci tests glob "library\\src\\commonTest\\kotlin\\**\\*Test.kt" "library\\src\\jvmTest\\kotlin\\**\\*Test.kt"

      #       echo "Forward slash glob:"
      #       circleci tests glob "library/src/commonTest/kotlin/**/*Test.kt" "library/src/jvmTest/kotlin/**/*Test.kt"
      - run:
          name: Build classnames list (PowerShell)
          shell: powershell.exe
          command: |
            circleci tests glob "library/src/commonTest/kotlin/**/*Test.kt" "library/src/jvmTest/kotlin/**/*Test.kt" `
            | % {
                $_ -replace '\\','/' `
                  -replace '^library/src/commonTest/kotlin/','' `
                  -replace '^library/src/jvmTest/kotlin/','' `
                  -replace '/','.' `
                  -replace '\.kt$',''
              } `
            | Tee-Object classnames.txt

            Write-Host "==== CLASSNAMES ===="
            Get-Content classnames.txt
      - run:
          name: Split tests
          shell: powershell.exe
          command: |
            Get-Content classnames.txt `
            | circleci tests run `
                --command="xargs -n1 echo" `
                --split-by=name `
                --timings-type=classname `
                --verbose

            # If this is a re-run and it is a parallel run that does not have tests to run, halt execution of this parallel run
            # [ -s classnames.txt ] || circleci-agent step halt
            if (-not (Test-Path classnames.txt) -or -not (Get-Content classnames.txt | Where-Object { $_.Trim() })) {
              circleci-agent step halt
            }
      - run:
          name: Run split tests
          shell: bash.exe
          command: |
            echo "Classnames selected for this node:"
            tr -d '\r' < cat classnames.txt

            tr -d '\r' < library/classnames.txt \
            | xargs -n1 -I{} echo ./gradlew :library:jvmTest --tests "{}" --no-daemon --stacktrace --info

            tr -d '\r' < library/classnames.txt \
            | xargs -n1 -I{} ./gradlew :library:jvmTest --tests "{}" --no-daemon --stacktrace --info


            # Format the arguments to "./gradlew jvmTest"
            # GRADLE_ARGS=$(cat library/classnames.txt | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
            # echo "Prepared arguments for Gradle: $GRADLE_ARGS"

            # ./gradlew :library:jvmTest $GRADLE_ARGS --no-daemon --stacktrace --info # Adjust path to gradlew if needed; use :library: prefix for subproject

      - store_test_results:
          path: library/build/test-results
  publish_to_maven_local:
    steps:
      - run:
          name: Publish to Maven Local
          command: ./gradlew publishToMavenLocal --no-daemon --stacktrace
  publish_and_backup_maven:
    steps:
      - run:
          name: Publish to custom local & backup
          command: |
            ./gradlew publishToMavenLocal -Dmaven.repo.local=/tmp/maven-local --no-daemon --stacktrace
            tar -czf /tmp/maven-local.tar.gz -C /tmp maven-local
      - store_artifacts:
          path: /tmp/maven-local.tar.gz
          destination: maven-local
  collect_test_results:
    steps:
      - run:
          name: Collect test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
  kover_xml_report:
    steps:
      - run:
          name: Generate Kover XML report
          command: ./gradlew koverXmlReport --no-daemon
  kover_html_report:
    steps:
      - run:
          name: Generate Kover XML report
          command: ./gradlew koverHtmlReport --no-daemon
  coveralls_coverage_upload:
    steps:
      - coveralls/upload:  # COVERALLS_REPO_TOKEN must be set in CircleCI project settings
          coverage_file: library/build/reports/kover/report.xml
  codacy_coverage_upload:
    steps:
      - coverage-reporter/send_report:  # CODACY_PROJECT_TOKEN must be set in CircleCI project settings
          coverage-reports: library/build/reports/kover/report.xml -l Kotlin final
          project-token: $CODACY_PROJECT_TOKEN
  save_gradle_cache:
    steps:
      - save_cache:
          key: gradle-v1-{{ checksum "/tmp/gradle-cache-key.txt" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
  save_konan_cache:
    steps:
      - save_cache:
          key: konan-v1-{{ checksum "/tmp/kotlin-cache-key.txt" }}
          paths:
            - ~/.konan
  save_m2_cache:
    steps:
      - save_cache:
          key: m2-v1-{{ checksum "/tmp/m2-cache-key.txt" }}
          paths:
            - ~/.m2
  prepare:
    steps:
      - checkout
      - extract_gradle_version
      - extract_kotlin_version
      - extract_m2_version
      - restore_gradle_cache
      - restore_konan_cache
      - restore_m2_cache
      - ensure_gradle_wrapper
      - accept_android_licenses
      - configure_kotlin_native
  cleanup:
    steps:
      - save_gradle_cache
      - save_konan_cache
      - save_m2_cache

jobs:
  coveralls-coverage-report:
    executor: gradle
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs=-Xmx4g"
    steps:
      - prepare
      - kover_xml_report
      - coveralls_coverage_upload
      - cleanup
  human-coverage-report:
    executor: gradle
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs=-Xmx4g"
    steps:
      - prepare
      - kover_html_report
      - cleanup
  build-and-test:
    executor: windows # << pipeline.parameters.platform >>
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs=-Xmx4g"
    steps:
      - prepare
      # - run_build
      - run_tests
      - cleanup
  publish-local-artifacts:
    executor: gradle
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs=-Xmx4g"
    steps:
      - prepare
      - publish_and_backup_maven
      - cleanup

parameters:
  action:
    type: enum
    enum: [test, coverage, report]
    default: test
  platform:
    type: enum
    enum: [gradle, macos, windows]
    default: gradle

workflows:
  #  version: 2
  #  ci:
  #    jobs:
  #      - publish-local-artifacts
  coverage:
    when:
      equal: [ coverage, << pipeline.parameters.action >> ]
    jobs:
      - coveralls-coverage-report
  report:
    when:
      equal: [ report, << pipeline.parameters.action >> ]
    jobs:
      - human-coverage-report
  test:
    when:
      equal: [ test, << pipeline.parameters.action >> ]
    jobs:
      - build-and-test
